# Generated by Django 5.0.3 on 2024-03-09 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('date_of_release', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('provider', models.CharField(blank=True, max_length=150, null=True, verbose_name='Поставщик')),
                ('debit_to_the_provider', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность перед поставщиком')),
                ('creation_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
                'ordering': ('-city',),
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('provider', models.CharField(default='(<django.db.models.fields.CharField>, <built-in function id>)', verbose_name='Поставщик')),
                ('debit_to_the_provider', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность перед поставщиком')),
                ('creation_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
                'ordering': ('-city',),
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('provider', models.CharField(blank=True, max_length=150, null=True, verbose_name='Поставщик')),
                ('debit_to_the_provider', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность перед поставщиком')),
                ('creation_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
                'ordering': ('-city',),
            },
        ),
        migrations.CreateModel(
            name='ProviderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.IntegerField(verbose_name='id провайдера')),
                ('debit_to_the_provider', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность перед поставщиком')),
                ('individual_entrepreneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.individualentrepreneur')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Продукты')),
                ('retail_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.retailnetwork')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
