# Generated by Django 5.0.3 on 2024-03-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_thelinkofthenetwork_delete_providerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='products',
        ),
        migrations.RemoveField(
            model_name='retailnetwork',
            name='products',
        ),
        migrations.AlterModelOptions(
            name='thelinkofthenetwork',
            options={'ordering': ('-city',), 'verbose_name': 'Звено сети', 'verbose_name_plural': 'Звенья сети'},
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='IndividualEntrepreneur',
        ),
        migrations.DeleteModel(
            name='RetailNetwork',
        ),
    ]
